### ISSUE TITLE
more bugs?

### ISSUE THREAD

**Issue by caspervanneck** [PocketDreams/SequinLand-Glowstone#10]
not all chunks load or generrate only  1 chunk and you stap out of chunk you bugt

**Comment by caspervanneck** [comment]
and players have a string bij entitys

**Comment by MrPowerGamerBR** [comment]
The first one is because the client position isn't updated on the server, so the server never tries to send new chunks to the client.

**Comment by caspervanneck** [comment]
@MrPowerGamerBR player survivel not compleat working?

**Comment by DaMatrix** [comment]
There's almost nothing that works completely now, son don't expect it to.

**Comment by MrPowerGamerBR** [comment]
@caspervanneck yes, almost nothing is working yet.

If you want to create a MCPE server in Java, you will need to use Nukkit while this isn't 100% done.

**Comment by caspervanneck** [comment]
i know but i test @MrPowerGamerBR

**Comment by DaMatrix** [comment]
There's not really anything to test yet lol

**Comment by MrPowerGamerBR** [comment]
Fixed the leash bug
