### ISSUE TITLE
is this dead

### ISSUE THREAD

**Issue by caspervanneck** [PocketDreams/SequinLand-Glowstone#19]
No update at latest days?.

**Comment by MrPowerGamerBR** [comment]
The project is now obsolete due to ProtocolSupportPE. I'm now working on my Minecraft PC network and in ProtocolSupportPE, I just forgot to update this project readme (and my Nukkit fork readme too)

**Comment by caspervanneck** [comment]
your fork or ofcial fork

**Comment by caspervanneck** [comment]
@MrPowerGamerBR

**Comment by MrPowerGamerBR** [comment]
@caspervanneck my fork
